"use client";
import { useEffect, useState } from "react";
import { db } from "@/lib/firebase";
import { doc, getDoc } from "firebase/firestore";

export default function MediaKit({ params }) {
  const [data, setData] = useState(null);

  useEffect(() => {
    const getKit = async () => {
      // Ищем юзера по коду из URL
      const docSnap = await getDoc(doc(db, "users", params.code));
      if (docSnap.exists()) {
        setData(docSnap.data());
      }
    };
    getKit();
  }, [params.code]);

  if (!data) return <div style={{padding: '50px', textAlign: 'center'}}>Загрузка официального медиакита...</div>;

  // Если делали аудит, данные лежат в lastStats
  const stats = data.lastStats || { subs: "Не пройдена аналитика", views: "Нет данных" };

  return (
    <main style={{ padding: '60px', maxWidth: '800px', margin: '0 auto', background: '#fff', minHeight: '100vh', fontFamily: 'sans-serif' }}>
      <header style={{ textAlign: 'center', marginBottom: '60px' }}>
        <span style={{ fontSize: '80px' }}>{data.avatar}</span>
        <h1 style={{ fontSize: '48px', margin: '10px 0', color: '#111' }}>{data.name}</h1>
        <div style={{ background: '#ff7a50', color: '#fff', padding: '8px 20px', borderRadius: '50px', display: 'inline-block', fontWeight: 'bold', fontSize: '14px' }}>
          OFFICIAL YOUTUBE MEDIA KIT
        </div>
      </header>
      
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '40px' }}>
        <div style={{ padding: '30px', background: '#f9f9f9', borderRadius: '20px', border: '1px solid #eee' }}>
            <span style={{ color: '#888', fontSize: '12px', fontWeight: 'bold' }}>ПОДПИСЧИКИ</span>
            <div style={{ fontSize: '32px', fontWeight: '900', marginTop: '10px' }}>{stats.subs}</div>
        </div>
        <div style={{ padding: '30px', background: '#f9f9f9', borderRadius: '20px', border: '1px solid #eee' }}>
            <span style={{ color: '#888', fontSize: '12px', fontWeight: 'bold' }}>ПРОСМОТРЫ КАНАЛА</span>
            <div style={{ fontSize: '32px', fontWeight: '900', marginTop: '10px' }}>{stats.views}</div>
        </div>
      </div>

      <div style={{ padding: '40px', background: '#fff', borderRadius: '25px', border: '2px solid #eee' }}>
         <h3 style={{ fontSize: '24px', marginBottom: '20px' }}>Статистика и охваты</h3>
         <p style={{ fontSize: '16px', lineHeight: '1.8', color: '#444' }}>
           Профиль <b>{data.name}</b> прошел верификацию через Channel Scope AI. 
           Владелец канала имеет прямой доступ к профессиональной аналитике, 
           регулярно отслеживает вовлеченность аудитории и готов к рекламным интеграциям.
         </p>
         <div style={{ marginTop: '30px', padding: '20px', background: '#fff1ed', borderRadius: '12px', color: '#ff7a50', fontWeight: 'bold' }}>
            ID Профиля: {data.code}
         </div>
      </div>
      
      <footer style={{ marginTop: '60px', textAlign: 'center', color: '#ccc', fontSize: '12px' }}>
        Generated by Channel Scope AI © 2026
      </footer>
    </main>
  );
}
