"use client";
import { useEffect, useState } from "react";
import { db } from "@/lib/firebase";
import { doc, getDoc } from "firebase/firestore";

export default function MediaKit({ params }) {
  const [data, setData] = useState(null);

  useEffect(() => {
    const getKit = async () => {
      const docSnap = await getDoc(doc(db, "users", params.code));
      if (docSnap.exists()) setData(docSnap.data());
    };
    getKit();
  }, [params.code]);

  if (!data) return <div style={{padding: '50px', textAlign: 'center'}}>Загрузка профессионального профиля...</div>;

  return (
    <main style={{ padding: '50px', maxWidth: '1000px', margin: '0 auto', background: '#fff', minHeight: '100vh' }}>
      <header style={{ textAlign: 'center', marginBottom: '50px' }}>
        <span style={{ fontSize: '50px' }}>{data.avatar}</span>
        <h1 style={{ fontSize: '42px', margin: '10px 0' }}>{data.name}</h1>
        <div style={{ background: '#ff7a50', color: '#fff', padding: '5px 15px', borderRadius: '50px', display: 'inline-block', fontWeight: 'bold' }}>OFFICIAL YOUTUBE MEDIA KIT</div>
      </header>
      
      <div style={{ padding: '40px', background: '#f9f9f9', borderRadius: '25px', border: '2px solid #ff7a50' }}>
         <h2>Статистика охватов</h2>
         <p>Этот профиль подтвержден системой Channel Scope AI. Владелец имеет прямой доступ к аналитике и готов к рекламным интеграциям.</p>
         <div style={{ fontSize: '24px', marginTop: '20px' }}>
            ID Профиля: <strong>{data.code}</strong>
         </div>
      </div>
      <p style={{ marginTop: '40px', textAlign: 'center', color: '#999' }}>Generated by Channel Scope AI © 2026</p>
    </main>
  );
}
